# Generated by Django 4.2.1 on 2023-07-02 05:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('cmms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('note', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='pm_frequency',
            field=models.CharField(
                choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily'), ('H', 'Hourly'), ('N', 'Never')],
                default='M',
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name='timer',
            name='repeat_frequency',
            field=models.CharField(
                blank=True,
                choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily'), ('H', 'Hourly'), ('N', 'Never')],
                default='M',
                max_length=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='Sparepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('picture', models.CharField(blank=True, default='', max_length=32)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmms.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
