name: Build

on:
  push:
    branches:
      - dev
      - django
    tags:
      - 1.*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'fatx64/cmms'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push (Nightly)
        uses: docker/build-push-action@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref_name == 'dev' && github.repository == 'fatx64/cmms' }}
        with:
          context: .
          push: true
          tags: ghcr.io/fatx64/cmms:nightly

      - name: Build and push (Canary)
        uses: docker/build-push-action@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref_name == 'django' && github.repository == 'fatx64/cmms' }}
        with:
          context: .
          push: true
          tags: ghcr.io/fatx64/cmms:canary

      - name: Build and push (Release)
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'fatx64/cmms'
        with:
          context: .
          push: true
          tags: |
            ghcr.io/fatx64/cmms:latest
            ghcr.io/fatx64/cmms:${{ env.VERSION_TAG }}